using Weasyprint.Wrapped;

var printer = new Printer(new ConfigurationProvider());
Console.WriteLine("Start initializing wrapper");
await printer.Initialize();
Console.WriteLine("Done initializing wrapper");
Console.WriteLine("Version");
var versionResult = await printer.Version();
Console.WriteLine($" - ExitCode:            {versionResult.ExitCode}");
Console.WriteLine($" - HasError:            {versionResult.HasError}");
Console.WriteLine($" - Error:               {versionResult.Error}");
Console.WriteLine($" - RunTime:             {versionResult.RunTime}");
Console.WriteLine($" - Version:             {versionResult.Version}");
Console.WriteLine("Start printing");
var result = await printer.Print(File.ReadAllText("../Weasyprint.Wrapped.Tests/Expected/Print_RunsCommand_SpecialCharacters_Input.html"));
Console.WriteLine("Done printing");
Console.WriteLine($" - ExitCode:            {result.ExitCode}");
Console.WriteLine($" - HasError:            {result.HasError}");
Console.WriteLine($" - Error:               {result.Error}");
Console.WriteLine($" - RunTime:             {result.RunTime}");
Console.WriteLine($" - Bytes(length):       {result.Bytes.Length}");
File.WriteAllBytes("result.pdf", result.Bytes);
